### ISSUE TITLE
Cybery name for boosts

### ISSUE THREAD

**Issue by jemus42** [Chronister/mastodon#1]
Suggestions:

- Propagations
- Copies
- Clones
- Combo

… Idunno. Also see https://cybre.space/@nightpool/116701

**Comment by chr-1x** [comment]
I made a poll here, feel free to vote on your favorite option(s): http://www.polltab.com/BkKwsUupe

**Comment by Cassolotl** [comment]
I voted "other" - it's silly, I know, but I feel so much better when the words sound like what they do in a very clear direct way! I'm pretty comfy with "ping", but "boost" confuses me. I just end up intuitively calling it post, repost, save.

So, my vote is for "repost". XD I can imagine that will not happen, since the instance's word for *save* is "florp"! But I thought I'd mention, since you asked me to in the poll.

**Comment by nightpool** [comment]
I voted boost instantiate and other, mainly because I think there's still possibility space yet untapped here. instantiate sounds best as a verb though, IMO.

**Comment by chr-1x** [comment]
Round two of the poll -- http://www.polltab.com/Hy2Ok__pg

**Comment by chr-1x** [comment]
final round of the poll -- http://www.polltab.com/ryVDyIKTx
